(function() {
    'use strict';

    /**
     * @enum {string}
     */
    const ZaliNativeMessageTypes = Object.freeze({
        ADD_CONTACT_REQUEST: "ADD_CONTACT_REQUEST",
        API_REQUEST: "API_REQUEST",
        AUTH_REQUEST: "AUTH_REQUEST",
        CLOSE_WINDOW: "CLOSE_WINDOW",
        DELETE_AVATAR_REQUEST: "DELETE_AVATAR_REQUEST",
        DOWNLOAD_ATTACHMENT: "DOWNLOAD_ATTACHMENT",
        DOWNLOAD_UPDATE_REQUEST: "DOWNLOAD_UPDATE_REQUEST",
        INSTALL_UPDATE_REQUEST: "INSTALL_UPDATE_REQUEST",
        LOAD_AVATAR_REQUEST: "LOAD_AVATAR_REQUEST",
        LOAD_SERVER_HISTORY: "LOAD_SERVER_HISTORY",
        MAXIMIZE_WINDOW: "MAXIMIZE_WINDOW",
        MINIMIZE_WINDOW: "MINIMIZE_WINDOW",
        NETWORK_CONFIG: "NETWORK_CONFIG",
        PERSIST_DEVICE_IDENTITY: "PERSIST_DEVICE_IDENTITY",
        REFRESH_HISTORY: "REFRESH_HISTORY",
        REMOVE_CONTACT_REQUEST: "REMOVE_CONTACT_REQUEST",
        RESOLVE_TENOR: "RESOLVE_TENOR",
        SAVE_MESSAGE_CACHE: "SAVE_MESSAGE_CACHE",
        SAVE_PENDING_OUTBOX: "SAVE_PENDING_OUTBOX",
        SAVE_STYLE: "SAVE_STYLE",
        SEND_MESSAGE: "SEND_MESSAGE",
        SET_KEY: "SET_KEY",
        SET_MESSAGE_REACTION: "SET_MESSAGE_REACTION",
        SET_SESSION: "SET_SESSION",
        SET_UNREAD_BADGE: "SET_UNREAD_BADGE",
        SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
        START_DRAG: "START_DRAG",
        START_SCREEN_CAPTURE: "START_SCREEN_CAPTURE",
        STOP_SCREEN_CAPTURE: "STOP_SCREEN_CAPTURE",
        UPLOAD_AVATAR_REQUEST: "UPLOAD_AVATAR_REQUEST",
        VOICE_EVENT: "VOICE_EVENT",
    });

    window.ZaliNativeMessageTypes = ZaliNativeMessageTypes;
})();
