import Foundation

enum BridgeProtocolMessageType: String, CaseIterable {
    case addContactRequest = "ADD_CONTACT_REQUEST"
    case apiRequest = "API_REQUEST"
    case authRequest = "AUTH_REQUEST"
    case closeWindow = "CLOSE_WINDOW"
    case deleteAvatarRequest = "DELETE_AVATAR_REQUEST"
    case downloadAttachment = "DOWNLOAD_ATTACHMENT"
    case downloadUpdateRequest = "DOWNLOAD_UPDATE_REQUEST"
    case installUpdateRequest = "INSTALL_UPDATE_REQUEST"
    case loadAvatarRequest = "LOAD_AVATAR_REQUEST"
    case loadServerHistory = "LOAD_SERVER_HISTORY"
    case maximizeWindow = "MAXIMIZE_WINDOW"
    case minimizeWindow = "MINIMIZE_WINDOW"
    case networkConfig = "NETWORK_CONFIG"
    case persistDeviceIdentity = "PERSIST_DEVICE_IDENTITY"
    case refreshHistory = "REFRESH_HISTORY"
    case removeContactRequest = "REMOVE_CONTACT_REQUEST"
    case resolveTenor = "RESOLVE_TENOR"
    case saveMessageCache = "SAVE_MESSAGE_CACHE"
    case savePendingOutbox = "SAVE_PENDING_OUTBOX"
    case saveStyle = "SAVE_STYLE"
    case sendMessage = "SEND_MESSAGE"
    case setKey = "SET_KEY"
    case setMessageReaction = "SET_MESSAGE_REACTION"
    case setSession = "SET_SESSION"
    case setUnreadBadge = "SET_UNREAD_BADGE"
    case showNotification = "SHOW_NOTIFICATION"
    case startDrag = "START_DRAG"
    case startScreenCapture = "START_SCREEN_CAPTURE"
    case stopScreenCapture = "STOP_SCREEN_CAPTURE"
    case uploadAvatarRequest = "UPLOAD_AVATAR_REQUEST"
    case voiceEvent = "VOICE_EVENT"
}
